# Generated by Django 5.0.3 on 2024-03-29 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(max_length=100)),
                ('barba', models.IntegerField()),
                ('corte', models.IntegerField()),
                ('descrição', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='AppBarb.plano')),
            ],
        ),
    ]
