# Generated by Django 5.0.3 on 2024-03-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco',
            new_name='endereço',
        ),
    ]
