# Generated by Django 5.0.3 on 2024-03-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0002_rename_endereco_cliente_endereço'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='data_final',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='data_inicio',
        ),
    ]
