# Generated by Django 5.0.3 on 2024-03-29 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0003_remove_plano_data_final_remove_plano_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='descrição',
        ),
    ]
