# Generated by Django 5.0.3 on 2024-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0005_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='observações',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
