# Generated by Django 5.0.3 on 2024-03-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0006_alter_agendamento_observações'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='observações',
            new_name='observacao',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='metodoPgto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='statusPgto',
            field=models.CharField(choices=[('pg', 'Pago'), ('faltapg', 'Falta Pagamento')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora',
            field=models.DateTimeField(default=0),
        ),
    ]
