# Generated by Django 5.0.3 on 2024-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0008_alter_agendamento_metodopgto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='metodoPgto',
            field=models.CharField(choices=[('pix', 'pix'), ('cartao', 'cartao'), ('dinheiro', 'dinheiro'), ('fiado', 'fiado')], max_length=100, null=True),
        ),
    ]
