# Generated by Django 5.0.3 on 2024-03-31 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0009_alter_agendamento_metodopgto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_hora',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='idPlano',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='Id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBarb.cliente'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='Id_plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBarb.plano'),
        ),
    ]
