# Generated by Django 5.0.3 on 2024-03-31 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0010_remove_agendamento_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='Id_cliente',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='Id_plano',
            new_name='id_plano',
        ),
    ]
