# Generated by Django 5.0.3 on 2024-04-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0012_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='id_agenda',
        ),
    ]
