# Generated by Django 5.0.3 on 2024-04-03 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0013_remove_agenda_id_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBarb.cliente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBarb.plano'),
        ),
    ]
