# Generated by Django 5.0.3 on 2024-04-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0014_agenda_cliente_agenda_plano'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento',
            new_name='Contrato',
        ),
    ]
