# Generated by Django 5.0.3 on 2024-04-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0015_rename_agendamento_contrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
