# Generated by Django 5.0.3 on 2024-04-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0017_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='valor',
            field=models.FloatField(),
        ),
    ]
