# Generated by Django 5.0.3 on 2024-04-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBarb', '0018_alter_plano_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
